spring:
  jwt:
    secret: ${secret}
  tomcat:
    threads:
      max: 300
    max-connections: 1000
  datasource:
    hikari:
      maximum-pool-size: 500
      minimum-idle: 50
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coupons
    username: postgres
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 100
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE


